### PR TITLE
Added Tournaments Tab to Navigation Bar

### PR DESCRIPTION
**Pull request by rqueiroz20**
This PR is used to address #207 and adds a "Tournaments" tab to the navigation bar if a user is logged into ChiGame.

### CODE REVIEW

**Review by MikeChen012345 — APPROVED** [review]
I have tested the code locally, and it seems that it fits with the code in the dev branch nicely. Since this is a relatively small change and no other files are modified, it should be good to go. Good job!

**Review by elizabethli31 — APPROVED** [review]
Looks good to me! Can you rebase and I'll merge?

**Comment by rqueiroz20** [comment]
Here is a summary of what everyone did for this simple PR, which involved adding a Tournaments tab for navigation at the top of ChiGame when a user is logged in:

- Because this task was relatively small, Riyush Thakur and I met together to work on this together. 
- I wrote up the code that initially modified `base.html` and Riyush realized that I had forgotten to implement the user authentication portion that I had mentioned in the PR description. So he went ahead and modified my code.
- From there, I created the PR and had Zihao Chen review it.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good work! Minor change, but provides much greater functionality.

**Pull request merged**
