### PR TITLE
Added remove friend logic

### LINKED ISSUE #332: Allow for removing Friends
The Remove Friend button on profile pages now does not direct to anything. We need to create a remove friend functionality. Users can not remove friends while logged out or remove other users they are not friends with or users that do not exist. Moreover, this function should also remove the friend invite that exists between these two users.

### PR DESCRIPTION
**Pull request by omarelkashef**
We added functionality to the Remove Friend button on profile pages that removes the two users from each other friend lists and delete the friend invite that exists between these two users. Users can not remove friends while logged out or remove other users they are not friends with or users that do not exist.

### CODE REVIEW

**Review by 24raniwalar — APPROVED** [review]
Button works well on local testing. Nice job adding a "unfriend_users" view as well. Keep up the good work!

**Review by elizabethli31 — APPROVED** [review]
Logic is perfectly sound, and I really like the addition/usage of the FriendInvitationManager as well as the separation of unfriending functionality from the actual remove friend view. LGTM and great job!

**Comment by omarelkashef** [comment]
Closing Statement:  Remove Friend button on profile pages now works. Users can not remove friends while logged out or remove other users they are not friends with or users that do not exist.
@AndrewM131 @henrietta-k  worked on the view function for removing friends
@omarelkashef  worked on on the logic of unfriending users

**Comment by AndrewM131** [comment]
Closing Statement: Remove Friend button on profile pages now works. Users can now remove friends while logged out or remove other users they are not friends with or users that do not exist.
Team contributions in issue closing statement.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Same comments as issue - good work!

**Pull request merged**
