### PR TITLE
created sandbox directory

### LINKED ISSUE #174: Create a sandbox directory in the chigame repo
This task is to create a new sandbox directory in the chigame repo to be used for testing and evaluation of the django-machina ( #145 ) and Misago ( #146 ) forum libraries, and also to be available for future use. Per the guidance of @majorsylvie, this directory should reside at `/src/sandbox`.

### PR DESCRIPTION
**Pull request by joshuamonroe**
Created a sandbox directory (w/ readme) for the purpose of testing and evaluating code independently of the rest of the chigame codebase ( #174 ). This directory has been created to support the evaluation of the django-machina ( https://github.com/uchicago-cs/chigame/issues/145 ) and Misago ( https://github.com/uchicago-cs/chigame/issues/146 ) forum libraries, but will remain available for future use. Per the guidance of @majorsylvie, this directory is located at /src/sandbox.

### CODE REVIEW

**Comment by bburgess19** [comment]
Forced a reset to a previous commit because I added code not germane to this PR.

**Review by giomhern — APPROVED** [review]
This adequately sets up a sandbox folder and I think it is a good idea to include README for future developers. Text is concise and well-put.

**Review by majorsylvie — APPROVED** [review]
Thank y'all for making this!

README is a great touch. 

Good to merge

**Comment by joshuamonroe** [comment]
Closed and merged to dev without significant revision. Thanks to @giomhern for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work y'all! 

Nice verbose review @giomhern 
Great job with formatting and linking relevant issues in the summary @joshuamonroe 

Happy to see the sandbox merged and functional

**Pull request merged**
