### PR TITLE
(user profiles) Add friend invitations endpoints

### LINKED ISSUE #29: (user profiles) Add friend invitations endpoints
We need endpoints to allow users to send and cancel friend requests. Profile pages need to reflect the status of a friend request. That is, it should display an Add Friend button if users are not friends and there is no friend invitation already and Remove Friend button if they are already friends and Cancel Friend Request if users are not friends but there is friend invitation already.

### PR DESCRIPTION
**Pull request by omarelkashef**
Create endpoints to allow users to send and cancel friend requests. Profile pages need to reflect the status of a friend request. That is, it should display an Add Friend button if users are not friends and there is no friend invitation already and Remove Friend button if they are already friends and Cancel Friend Request if users are not friends but there is friend invitation already.

### CODE REVIEW

**Review by henrietta-k — APPROVED** [review]
Looks good to me! Good job catching errors as well

**Review by elizabethli31 — APPROVED** [review]
LGTM! Endpoints all work well.

**Comment by omarelkashef** [comment]
Closing statement: We added endpoints for sending and canceling friend request. The profile page reflects the status of this request through Add Friend, Remove Friend, Cancel Friend Request buttons.  Accepting a FriendInvitation through admin site is the admin's responsibility since that change will not be reflected in the app in this issue.

@omarelkashef worked on creating new friending endpoints 
@24raniwalar worked on making the profile page buttons use of the new endpoints

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great job! Your code looked great and again, very thorough error handling.

**Pull request merged**
