### PR TITLE
Created Chigame Logos and Icon

### LINKED ISSUE #308: Icon and Logo
It would be nice to have a logo/icon as branding. The goal of this issue will be to document the process of creating a logo and the final output will be a pull request with a logo and icon in the static images folder.

### PR DESCRIPTION
**Pull request by frowenz**
### Changes
In this PR, I have added Chigame logo and icon images to the repo including the photoshop files that were used to make these images. Currently, the logos are in `src/static/images/logos` and the favicon is in`src/static/images/favicons`. Finally, I changed the `favicon` in the corresponding code and added the logo to the navbar.

### Images

logo_filled
Screenshot 2023-11-28 at 1 23 51 PM

> Corresponding issue: #308

### CODE REVIEW

**Comment by bburgess19** [comment]
These logo looks awesome, and I see the favicon is updated as well. To anyone who gets a large image, force a page refresh on your appropriate browser/OS (it was shift + CMD + R on my mac) to get the updated css.

image

**Review by bburgess19 — APPROVED** [review]
These logo looks awesome, and I see the favicon is updated as well. To anyone who gets a large image, force a page refresh on your appropriate browser/OS (it was shift + CMD + R on my mac) to get the updated css.
image

**Review by majorsylvie — APPROVED** [review]
Thank you for your effort! 

Really cool to have a logo and actual favicon now.

**Comment by frowenz** [comment]
Closing comment: 

I created a logo using a combination of photoshop and generative AI. This logo was added to the navbar and as a favicon. Currently, all logo related files are in `src/static/images/logos` and the favicon is in `src/static/images/favicons`.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Minor PR but not issue, since the only code this is adding is image.
Great work! Especially good closing comment which concisely communicates what was done and the relevant locations for the images.

Thank you for your work. We're almost done with the quarter!

**Pull request merged**
