### PR TITLE
Added a more realistic fixture for lobbies

### LINKED ISSUE #248: Create an updated fixture for lobbies with realistic names and games
**Goal:** We currently only have fixtures with one game instance and one lobby instance. To test lobby filters and other future functionalities, we want to update the fixtures to include more model instances with unique/realistic names rather than simple names like `test lobby1`

**Deliverables:**
- PR

### PR DESCRIPTION
**Pull request by jiyeongchloe**
We currently only have fixtures with one game instance and one lobby instance. To test lobby filters and other future functionalities, we want to update the fixtures to include more model instances with unique/realistic names rather than simple names like `test lobby1`
This uses the `users_fixture.json` and `games-fixture-5.json` that were already existing. The user passwords are the same as those in `users_fixture.json`

### CODE REVIEW

**Review by xylucien — APPROVED** [review]
Nice, I'm really glad we now have a much larger fixture to play around with. The fixture looks good to me!

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
Yay this'll make testing so much easier! I'm requesting changes because I'm not sure what this migration is because you didn't change any models. Also, I noticed that the members are all listed as "none" because that's the way the user model and your lobby_detail is set up. It could be worth creating a minor PR to use name in lobby_detail instead.

**Review by elizabethli31 — APPROVED** [review]

**Comment by jiyeongchloe** [comment]
**Closing Comment:**
PR is merged and finished.
Nat and Chloe: pulled existing user and games fixtures and added 15 lobbies to create a new fixture for lobbies

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
I like that the fixture built on top of already existing ones. Great work.

**Pull request merged**
