### PR TITLE
Added django-machina demo to the sandbox

### LINKED ISSUE #145: Install example instance of django-machina to the chigame sandbox directory
The objective of this task is to set up a default example instance of the django-machina forum library, verify that it runs correctly, and upload it to the chigame repo's sandbox directory (`src/sandbox`). This example instance will serve as the basis of a mock implementation ( #149 ) of the chigame forum that will be used for testing and evaluation purposes ( #99 ).

### PR DESCRIPTION
**Pull request by joshuamonroe**
I've added a demo version of django-machina to the sandbox directory. This demo is adapted from the example project provided in the [django-machina repo](https://github.com/ellmetha/django-machina) and is intended to be used for testing and evaluation purposes. I've included a readme with instructions on how to run the demo and a requirements file to load additional dependencies.

### CODE REVIEW

**Review by majorsylvie — APPROVED** [review]
Looks really nice! 

Happy we've been able to choose machina and get moving quickly.

This is a great example of sandboxable code. 
Excited to see y'all flesh this out more as you keep going!

**Review by Benjoman12 — APPROVED** [review]
This implementation looks good.

**Comment by joshuamonroe** [comment]
Closed and merged to dev without significant revision. Thanks to @Benjoman12  for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Nice and straightforward PR.

Thank you for the good summary of the work and outcome @joshuamonroe!

**Pull request merged**
