### PR TITLE
Small five game fixture added

### PR DESCRIPTION
**Pull request by frowenz**
In issue #98, we discussed the need for game fixtures. We decided to make fixtures of 5, 50 and 500 games. However, the larger fixtures have been blocked by other tasks for a while. Hence, we have decided to split these up into separate pull requests. 

In this pull request, we are merging in 5 game small fixtures.

### CODE REVIEW

**Review by ptlin25 — APPROVED** [review]
Without the updated detail page, not all of the game details are displayed, but from what I can see, the 5-game fixture looks good to go

**Comment by willcravitz** [comment]
I moved the file from `src/fixtures` into `src/chigame/games/fixtures` because the users team added their fixtures in `src/chigame/users/fixtures`.

**Review by majorsylvie — APPROVED** [review]
LGTM! Happy to see this so we can more easily manually test things like the grid display and detail views!

**Comment by willcravitz** [comment]
Closing comments: We created a fixture file `src/chigame/users/fixtures/games-fixture-small.json` with five games along with categories, mechanics, publishers, designers for those games. 

Developer contributions: @willcravitz wrote the initial draft of the fixture with the help of generative AI, and @frowenz reviewed, tested and kept the branch clean for the PR. @ptlin25 reviewed the PR.

We're keeping issue #98 open until we add medium and large fixture files. This issue should close with PR #246.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work y'all!
@willcravitz awesome closing comment. Clear, concise, yet mentioning a lot of very relevant details (like related issues/PR's).

Thank you all for your work!

**Pull request merged**
