### PR TITLE
Update the tournament models and provide support for managing tournament models in the admin interface

### PR DESCRIPTION
**Pull request by MikeChen012345**
In this pull request, we have made some changes to
- allow developers to access the tournament models through the admin interface (admin.py).
- add a num_winner field to the tournament model to keep track of the number of winners for a tournament.
- make the matches and players fields of the tournament model optional during the creation and edition of a tournament such that users can join and withdraw from a tournament by themselves instead of from direct assignment. Also, matches are made optional because they should be created through the bracket assignment mechanism in issue #163

### CODE REVIEW

**Review by jb-01 — APPROVED** [review]
- The `num_winner` field is added to the `tournament` model to represent the number of winners
- The `tournament` model is modified to support the tournament bracket functionality through the `winners` field
- The admin interface has improved support for handling models

The code modifications in both `models.py` and `admin.py` appear to satisfy the requirements outlined in issue #206.

Great work!

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
LGTM! Rebase with dev and I'll approve. I think you might get some merge conflicts with the migration, so you might want to delete your current migration, pull, then migrate again.

**Review by elizabethli31 — APPROVED** [review]
LGTM! Thanks for clarifying num_winner. Good work!

**Comment by MikeChen012345** [comment]
The pull request has been merged. This one took much less time than the previous two on the CRUD pages. During the process,
The code was done by Mike, Sam, and Riyush. Mike, Sam, and Riyush mainly worked on determining the fields that need to be modified for some future functionalities and discussed some possible ways of implementation. Later, Mike and Sam implemented the changes to the model and added an admin interface for easier creation of instances.
The reviewer was Joshua. He tested the code and assured that it worked as expected. Thanks!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Good minor change that improves tournaments functionality and implementation!

**Pull request merged**
