### PR TITLE
Allows users to perform bulk actions on notifications via checkboxes

### LINKED ISSUE #353: Add the option for bulk actions on Notifications
In the current inbox page, users can only do an action one notification at a time and each time the page will refresh. We need to allow users to select multiple notifications and do the same action on all of them. Notifications should also be marked as read once they are clicked by a user.

### PR DESCRIPTION
**Pull request by 24raniwalar**
In this PR, we add functionality such that in a user's inbox, they may check multiple notifications using checkboxes and then perform mass delete or read operations by pressing a delete or read button. To do so, we add a view function that handles actions when a POST request is sent from the buttons and use a form to track the status of checkboxes and buttons. We are also marking a notification as read once it is clicked by the user.

### CODE REVIEW

**Comment by 24raniwalar** [comment]
The PR currently has many files that will eventually be merged with PR 344 so this PR is essentially an extension. We branched off of origin/notifications-junk-box, the branch associated from PR 344. Waiting to request review until PR 344 is passed.

**Comment by omarelkashef** [comment]
We will also be adding some logic to mark a notification as read once it is clicked which was missed in #125  per a suggestion by @elizabethli31. The Issue and PR descriptions has been edited to reflect that.

**Review by ishiii-s — APPROVED** [review]
Code looks good to me. URLs.py sets the url paths, views method addresses the ability for users to check multiple notifications using checkboxes in their inbox and then perform mass delete or read operations by pressing corresponding buttons, as well as marking as read. Template file logic for html also doesn’t seem to have any erroneous logic. 

Only thought is if get_object_or_404 would be helpful instead of …objects.get to handle exceptions. Not requesting a change because code still seems to address PR objectively accurately!

**Review by elizabethli31 — APPROVED** [review]
PR looks good to go! Thanks for the additions of marking as read when clicked on and also fixing the remove friend edge case.

**Comment by 24raniwalar** [comment]
Closing comment: In this PR, users may now mark all notifications as read or delete all notifications using a checkbox next to each notification and buttons for the actions. Both developers worked on all parts of the PR.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Like my comment on the associated issue, this PR added some nice new functionality for notifications!

**Pull request merged**
