### PR TITLE
Created users-friends fixture file

### LINKED ISSUE #31: (user profiles) create sample user profile page

### PR DESCRIPTION
**Pull request by henrietta-k**
Addressing issue #31 

Created a fixture file with sample Users and userProfiles.

### CODE REVIEW

**Comment by 24raniwalar** [comment]
I think it may be a good idea to add a userprofile for the admin user as well, but other than that LGTM!

**Review by 24raniwalar — CHANGES_REQUESTED** [review]
I think it may be a good idea to add a userprofile for the admin user as well, but other than that LGTM!

**Comment by ishiii-s** [comment]
> I think it may be a good idea to add a userprofile for the admin user as well, but other than that LGTM!

Thanks for the review Rishabh! I believe we already have an admin user in the file, which is user 1 (is_staff is set to true). Let us know if that checks out or if we still be to make changes for an admin.

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
Agreed with Rishabh. I believe what he's saying is to add a userprofile for the admin user. Also, please make a new directory for user fixtures "src/chigame/users/fixtures" and move this file there.

**Comment by henrietta-k** [comment]
Turns out the userProfile instance for the admin was there but it had a primary key of 5 for some reason. I've updated all the primary keys for the userProfile to match their corresponding users. I also moved the file into a new folder.

**Comment by henrietta-k** [comment]
Turns out the userProfile instance for the admin was there but it had a primary key of 5 for some reason. I've updated all the primary keys for the userProfile to match their corresponding users. I also moved the file into a new folder.

**Review by 24raniwalar — APPROVED** [review]
LGTM! Nice revision

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
Did you guys create the users with the create_user method? I tested the fixture data, and I'm not able to sign in with the users and their passwords. The user profiles are showing up correctly though.

**Review by elizabethli31 — APPROVED** [review]
LGTM! Pull from the most updated dev and I'll merge. Great work!

**Comment by ishiii-s** [comment]
Closing Statment: 
We were able to successfully complete this PR. In this PR, @henrietta-k and @ishiii-s both worked together to figure out the general approach (e.g. how many users, what type of users), and both added code for sample users to the file. @henrietta-k then addressed the requested changes.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Like mentioned in the issue, this PR was super helpful for testing. Nice closing comment and thanks for addressing my changes. The description summary is a bit too terse, and I have taken a point off for that.

**Pull request merged**
