### PR TITLE
Created API Endpoint: GET list of friends of a user given `user_id` (ENDPOINT: `api/users/<int:user_id>/friends`)

### LINKED ISSUE #54: Create API Endpoint: GET list of friends given a user (ENDPOINT: `/api/users/<int:pk>/friends`)
**Goal**

We want to be able to get a list of friends given the `user_id` or primary key of the user. We should eventually make this list of friends be private if the user doesn't want to share the list of friends with everyone. This is useful so that a User can get their list of friends easily through the API. 

ENDPOINT: `/api/users/<int:user_id>/friends` -- this allows for the endpoint to know the specific user (user_id) to look at the friends for

We will know this issue is finished if we can use a GET request to get a list of the user's friends

### PR DESCRIPTION
**Pull request by abrahmasandra**
Created an endpoint `/api/users/<int:user_id>/friends` to get the list of friends of a user given the user's `id` (primary key of the user). This is useful so that someone can get the list of friends of a given user through the API.

Right now, there are no permissions needed for this (i.e. anyone can get the friend list of any other user using the API). Eventually, we may want to make the list of friends private, if specified by the given user. We may also want to support POST requests, so that a given user can make a friend request.

ENDPOINT: `/api/users/<int:user_id>/friends>` supports GET requests

Important Note: The issues for the List and Detail API Views of Users need to be implemented for this endpoint to be easily usable. This will make it possible for someone to easily add users, as well as access their `user_id` through the API, which can then be used to plug into this API endpoint.

### CODE REVIEW

**Review by cuyakonwu — APPROVED** [review]
LGTM!

**Review by majorsylvie — APPROVED** [review]
Nice clean use of django's ORM functionality to make a functional endpoint with easy-to-read code!

**Comment by abrahmasandra** [comment]
Closing Comment: Created an endpoint `/api/users/<int:user_id>/friends` that supports GET requests to get the list of friends of a user given the user's id (primary key of the user). This is useful so that someone can get the list of friends of a given user through the API.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
This issue could have used more updating comments! 
Especially with changes being made after the first reviewer.

Well written summary! Appreciate you also including extra information about the user views.

**Pull request merged**
