### PR TITLE
Updated Filtering Capabilities for Game List API Endpoint with Updated Game Model Attributes

### LINKED ISSUE #230: Update Filtering Capabilities for Game List API Endpoint with Updated Game Model Attributes
The `Game` model recently got updated to contain many more fields -- inspired by BoardGameGeek -- than just the four initial fields (name, description, max_players, min_players). We want our API endpoint to be able to handle filtering by any of the original fields (which we have already done), but also be able to filter by the new fields. Therefore, we need to add the new fields into the `GameFilter` class. 

We will know this issue is completed when we can filter by any field in the updated `Game` model.

### PR DESCRIPTION
**Pull request by abrahmasandra**
The Game model recently got updated to contain many more fields -- inspired by BoardGameGeek -- than just the four initial fields (name, description, max_players, min_players). We wanted our API endpoint to be able to handle filtering by any of the original fields (which we have already done), but also be able to filter by the new fields. 

This PR adds filtering by exact lookup for new integer type Game attributes including `year_published`, `suggested_age`, `expected_playtime`, `min_playtime`, `max_playtime`, `min_players`, `max_players`

In addition, it adds filtering based on `lte` and `gte` for the Decimal `complexity` attribute.

### CODE REVIEW

**Review by cuyakonwu — APPROVED** [review]
Looks great! This should also help us expand our querying for users, matches and tournaments as well!

**Review by majorsylvie — CHANGES_REQUESTED** [review]
**From testing this does not support exact `BGG_id` queries:**
`http://localhost:8000/api/games/?BGG_id=100`

But it does support the `gte` and `lte` queries on complexity:
`http://localhost:8000/api/games/?complexity__lte=3`
`http://localhost:8000/api/games/?complexity__gte=4.6`
as well as combined `gte` `lte` queries:
`http://localhost:8000/api/games/?complexity__lte=3&complexity__gte=2.9`
as well as combined with other queries:
`http://localhost:8000/api/games/?complexity__gte=4.6&max_players=2`

Please add support for BGG_id querying.

**Comment by abrahmasandra** [comment]
@majorsylvie added support for exact `BGG_id` filtering!

**Comment by abrahmasandra** [comment]
added support for `lte` and `gte` for additional `Game` model attributes including `year_published`, `max_players`, `min_players`, `max_playtime`, `expected_playtime`, `min_playtime`, `suggested_age`

**Review by majorsylvie — APPROVED** [review]
Looks great!

I can do queries such as:
```
http://localhost:8000/api/games/?max_players__gte=5&min_players__gte=3&complexity__lte=2
http://localhost:8000/api/games/?max_players__gte=5&min_players__gte=3&complexity__lte=2&name=int
http://localhost:8000/api/games/?BGG_ID=221
http://localhost:8000/api/games/?min_players__gte=4&max_players__lte=3
```
that last one being interesting since it actually returns a result in the current 500 game fixture:
image

Now this endpoint has much more meaningful composite querying. Thank you for your work.

Keep moving forward!

**Comment by abrahmasandra** [comment]
Closing Comment:

Updated the filtering capabilities of API `Game` list view. Specifically, now support filtering for all attributes in the `Game` model. All numeric attributes have support for filtering based on `exact`, `lte`, and `gte`. In addition, text attributes can be filtered using `icontains` (which filters by substring match). 

Endpoint implemented examples: 
1. `/api/games/?property1=key1`
2. `/api/games/?property1=key1&property2=key2`
3. `/api/games/?property1__lte=key1&property2__gte=key2`

**Comment by majorsylvie** [comment]
Issue Score: Excellent

**Pull request merged**
