### PR TITLE
Update tournament models to allow registration period and archive features

### PR DESCRIPTION
**Pull request by MikeChen012345**
Some changes has been made to the model:

- add `registration start date` and `registration end date` fields, which show the registration start and end date for the tournament.
- rename `start date` and `end date` into `tournament start date` and `tournament end date`.
- add restrictions to check the `num_winne`r, `max_players`, and `winners fields`.
- add restrictions to `registration start date`, `registration end date`, `tournament start date`, and `tournament end date`: The fields need to check that all registration and tournaments start/end date is after the moment that the tournament is created; also, the end date is after the start date; and registration start and end time are before the tournament start and end time.
- add tournament `status` field (@ property). The tournament status is calculated based on the tournament start and end date and registration start and end date (possible status: preparing, registration open, registration close, tournament in progress, tournament ended).
- add `archived` (default=False) field. An archived status is set if tournament 1. has closed 2. is marked as archived (because it is important) by admin users.
- add a set_archive method, which takes a boolean argument and sets the archived field based on the argument.
- modify the tournament list view and detail views such that the tournament status, registration start date, registration end date, and archive status are displayed. The archive status is represented by an icon, which will only be presented if the tournament has ended.
- modify the create view corresponding to the addition of `registration start date` and `registration end date`. 
- modify the update view. The dates now cannot be changed once the tournament has been created.

### CODE REVIEW

**Review by rqueiroz20 — APPROVED** [review]
Every feature that was changed was successfully reflected in my local display of ChiGame. Specifically, I did the following:

- I tried creating a tournament with the registration start and end date to be at my current time and was unable to (good).
- I tried creating a tournament with the registration start and end date to be after the tournament start date and was unable to (good).
- I tried creating a tournament with the number of winners greater than the max number of players in the tournament and was unable to (good).
- I tried creating a tournament with the registration start and end date to be before the tournament start date and was able to (good).

Once I successfully created the tournament, it displayed the `preparing` message in both the list and detail view. Once it crossed the registration start date, it updated to `registration open` on both views. Once it crossed the registration end date, it updated to `registration closed` on both views. Once it crossed the tournament start date, it showed `tournament in progress` on both views. Once it crossed the tournament end date, it showed `tournament ended` on both views and displayed a transparent star. Once I set its status to archived, the star became golden. 

I believe this is everything within the scope of this PR. Nicely done!

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
Really wonderful job on this giant PR! Took me awhile to test with all the date times and different test cases, but the functionality is a huge step up. Only change requested is that I'm unable to set_archive with the icon. I think you aren't actually calling it anywhere. You might need to add a JS file or just add a script on the detail and list html pages that gets the icon image and performs set_archive on click.

**Comment by MikeChen012345** [comment]
Hi Elizabeth,
Currently the icon is not a button, so the set_archive function is not called. This functionality will be implemented in PR #329. Thanks!

**Review by elizabethli31 — APPROVED** [review]
LGTM! Again, really great work on this PR.

**Comment by MikeChen012345** [comment]
Thank you!

**Comment by MikeChen012345** [comment]
In this pull request,
@MikeChen012345 and @MuyanXie worked on implementing the code, and @jb-01  brainstormed and came up with different kinds of scenarios in which the status should be changed and what checks to be added.
@rqueiroz20 did the review, tested all the features, and provided feedback on whether there might be more possible situations that current checks do not cover. Thank you!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Big improvement from the previous rendition of the join feature!

**Pull request merged**
