### PR TITLE
Restructured API tests (for Game Endpoints) to use Factories and be consistent with new Game model 

### LINKED ISSUE #166: Update the API Tests dealing with Game model (Testing List and Detail Views)
In issue #164, we detailed the ways that the Game endpoints needed to be changed in order to have functional API Endpoints that display and allow for the creation of Game objects with all the new attributes added to the models. Now, we also need to update the tests for these API Endpoints, because the old tests did not take into account all the new attributes that would be added to the Game model. 

Changing these tests are mandatory for the PR #165 to pass, because these tests need to pass before the new code for the List and Detail views can be merged to the `dev` branch of the repository.

### PR DESCRIPTION
**Pull request by abrahmasandra**
In issue https://github.com/uchicago-cs/chigame/issues/164, we detailed the ways that the Game endpoints needed to be changed in order to have functional API Endpoints that display and allow for the creation of Game objects with all the new attributes added to the models. Now, we updated the tests for these API Endpoints, because the old tests did not take into account all the new attributes that would be added to the Game model.

Changing these tests are mandatory for the PR https://github.com/uchicago-cs/chigame/pull/165 to pass, because these tests need to pass before the new code for the List and Detail views can be merged to the dev branch of the repository.

WHAT WAS DONE:

Created `factories.py` file in which there is a `CategoryFactory`, `MechanismFactory`, and `GameFactory`. The `tests.py` file was renames to `test_api.py`. Inside the tests, the factories are now used to dynamically create dummy Game objects. The tests created include GET game list/detail views, PATCH a game, and DELETE a game. POST game test will be updated later once PR #165 is merged, as that PR changes the serializer class.

### CODE REVIEW

**Review by cuyakonwu — APPROVED** [review]
Code is looking good!

**Review by majorsylvie — APPROVED** [review]
Looks great! I appreciate the spacing between subclasses and groups of attributes, makes the code more readable.

Hope that making tests feels easier once you make more using these new factories!

**Comment by abrahmasandra** [comment]
Closing statement: updated the pytests to test the API functionality at the 2 games endpoints from list/detail views. Specifically, checked that the List view supports GET/POST requests, and the detail view supports GET/PATCH/DELETE requests. Inside the tests, a Game factory is now used to dynamically create dummy Game objects, which is much easier and more dynamic than manually creating JSON objects to POST/PATCH etc.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great work! 
Very descriptive title and excellently fleshed out summary.

@cuyakonwu in the future when reviewing a PR, even if there is nothing that you see as needing changes, please add some more detail to your review cmoment! especially if you're not adding comments in the code. 

It's good to both ask questions for things you are unsure about as well as compliment your team members on what's good with their code / PR!

Keep moving forward y'all.

**Pull request merged**
