### PR TITLE
Adding a friend list to user profiles where each friend links to the friend's profile page

### LINKED ISSUE #352: View list of your friends
In this issue, we hope to add a button to the "My Profile" section of a user's own profile that allows the user to see a list of their friends. Each item in the list should link to the friends' profile page so users may be able to remove friends.

### PR DESCRIPTION
**Pull request by 24raniwalar**
This PR adds a button to a user's own profile page that allows them to access a list of their friends. The list of friends contains a list of friend emails, each of which links to a friend's profile page.

### CODE REVIEW

**Review by ishiii-s — APPROVED** [review]
Code looks good and quite clear. urls.py sets up url path for friend list view effectively, views effectively create function to handle requests to view friend list , including errors such as accessing a friend list that is not the users, and template file creates accurately creates HTML template to visualize the friends-list and button, and redirect the user to the list when button is clicked. I don't think I see any issues in the code or any logical errors that could create problems in the future, and everything mentioned in the PR seems to be addressed in the code. From my pov, it looks good to go!

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
Friend list button and its associated view look wonderful - great work! I'm only requesting changes because I'm wondering if you guys will still be integrating FriendsTable, and also please fix the merge conflicts. Besides that, this PR looks good to go!

**Review by elizabethli31 — APPROVED** [review]
Nice usage of the friends table. LGTM - good work!

**Comment by 24raniwalar** [comment]
Closing comment:
This PR handles the friend list button functionality on a user's profile page. With the Friend List button, users are able to see a list of their friends displayed using a FriendTable. Each friend's email links to that friend's profile page. All assignees worked together on this functionality.

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Great work!

**Pull request merged**
