### PR TITLE
Create the join and withdraw from tournament functionality

### PR DESCRIPTION
**Pull request by MikeChen012345**
This functionality allows users to sign up for the tournament on the tournament-detail view and tournament-list view pages. There is a button named "join" that puts the user entity into the "players" table of the tournament. The user can also quit the list by clicking the button named "withdraw". If the user has already joined the tournament, an error message claiming that the user has already joined the tournament will be displayed. The same would happen if the maximum number of players has been reached. If the user is not in a tournament and clicks the "withdraw" button, the user will also receive an error message claiming that the user has not joined the tournament. Note that some more condition checks shall be done after the registration deadline is implemented: the join and withdrawal shall be done before the match assignment (brackets) starts, etc.

### CODE REVIEW

**Review by jb-01 — CHANGES_REQUESTED** [review]
Overall, your code effectively addresses the issue's requirements with some areas for future improvement.

**Suggested Enhancements for Join and Withdraw Functionality:**

1. **Registration Deadline Validation:** Implement logic to restrict joining/withdrawing based on a set registration deadline.
2. **Tournament Time Constraints:** Add checks to prevent joining/withdrawing once the tournament has started or after it has ended.

**Comment by MikeChen012345** [comment]
Hi Joshua,
Thanks for the advice! These features have been considered. However, I reckoned that including all these changes in one pull request may be too big a task, so I have split the registration period feature into another task. Please check the registration deadline issue for more upcoming information!

**Comment by jb-01** [comment]
Thanks for the update Mike. After retrying your branch I get the following error on the http://127.0.0.1:8000/games/tournaments/ page:
Screenshot 2023-11-27 at 9 29 18 AM

**Comment by MikeChen012345** [comment]
Hi Joshua, 
Could you try to flush and migrate before runserver to see if the problem still exists? Thanks!

**Comment by MikeChen012345** [comment]
Hi Joshua,
The branch has been updated to reflect updates in the dev branch. Thanks!

**Review by elizabethli31 — CHANGES_REQUESTED** [review]
The buttons work well, and they look great! I like how you are able to join and withdraw from the list view page as well. I think you would need to add another check for if the start date has passed. Other than that, great work covering all the other possibilities!

**Comment by MikeChen012345** [comment]
Hi Elizabeth,
Thank you for the suggestion! The check will be implemented in pull request #247. Thanks!

**Review by jb-01 — APPROVED** [review]
Thanks for clarifying the errors on my version of your branch Mike. It seems to be working now! 

Great job.

**Review by elizabethli31 — APPROVED** [review]
Login for joining and leaving a tournament is sound and well implemented. Stylistic choice to have buttons appear on list and detail view also make sense to me. LGTM!

**Comment by MikeChen012345** [comment]
Closing Statement:

@MikeChen012345 worked on coding the solution to this issue
@MuyanXie worked on documenting and researching the different scenarios in which the tournament can be joined
@Riyush worked on how joining an already-joined tournament and withdrawing from a not-joined tournament may result in an error message

@jb-01 reviewed our code and provided very valuable comments. Thanks!

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Similar comments to the associated issue - great job on this PR.

**Pull request merged**
