### PR TITLE
Fix the discrepancies between in the nav-bar found in the forums page

### LINKED ISSUE #324: Fix inconsistent nav bar offset on forums page
While integrating the nav bar into the forums page, a bug was discovered that causes the nav bar to have an inconsistent offset between the forums page and the rest of the website.

https://github.com/uchicago-cs/chigame/assets/86740254/bd80e8fc-261c-4a56-9978-fbd0196798fe

_Originally posted by @majorsylvie in https://github.com/uchicago-cs/chigame/pull/272#pullrequestreview-1756620033_

### PR DESCRIPTION
**Pull request by Benjoman12**
Per issue #324 I have fixed the styling discrepancies between the nav-bar found in the forums page versus the rest of the website.

### CODE REVIEW

**Review by joshuamonroe — APPROVED** [review]
Looks like a clean fix, good job! Approved to merge.

**Review by majorsylvie — APPROVED** [review]
Wonderful works as expected no jittering nor offset present anymore when switching between any of the tabs. 

Great work!

**Comment by Benjoman12** [comment]
The robust nature of the bootstrap code Django-Machina was pulling its styling from made finding the actual elements causing the issue very challenging but once found, this implementation was very straightforward. Additionally, by adding the edited CSS to an external file, we have laid the groundwork for future coders to add additional customization to the Django-Machina CSS. Thanks to @joshuamonroe for reviewing the PR.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

**Pull request merged**
