### PR TITLE
Added mock fixture to the django-machina demo

### LINKED ISSUE #149: Implement a simple mockup of the chigame forum in the django-machina sandbox instance
The objective of this task is to implement a simple mockup of the chigame forum in the django-machina sandbox instance created in issue #145. The mock implementation should consist of a basic outline of the potential layout and structure of the chigame forum, without the need for implementing new functionalities or involving any sort of detailed customization. The focus should be on ensuring that the implementation process is straightforward and well-documented. Any challenges encountered during the process, as well as any potential issues that may arise in future development, should be recorded for inclusion in the django-machina evaluation report in issue #99.

### PR DESCRIPTION
**Pull request by joshuamonroe**
To address issue #149, I've add a mock fixture file to the django-machina demo with some example users, categories, forums, topics, and posts. The mock fixture will help to demonstrate what the chigame forum might look like if we were implement it using django-machina. The first few models were made by hand and then handed off to generative AI to create additional models.

### CODE REVIEW

**Review by Benjoman12 — APPROVED** [review]
This mockup looks good and allows us to visualize the extent to which we will be able to utilize django-machina.

**Review by majorsylvie — APPROVED** [review]
Topical models and there are enough present to give a good demo of what machina can do!

I would appreciate some more information as to how you generated these fixtures! Neither the issue nor PR conversation makes mention of how these were made.

If they were made by hand and/or with Generative AI assistance, say so!

**Comment by joshuamonroe** [comment]
I've added additional details on how the models were generated to the original comment. The first few models were made by hand and then handed off to generative AI to create additional models.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Thank you for specifying your process in the closing comment!

**Pull request merged**
