### PR TITLE
Display search results as a grid and removed duplicate results

### LINKED ISSUE #304: Make search results unique and displayed as a grid
This issue involves two relatively minor fixes. First, the search results should only return unique games i.e. no duplicates. Next, the search results should be displayed as a grid instead of the generic list view.

### PR DESCRIPTION
**Pull request by ptlin25**
Duplicate search results when searching for games has been removed by adding `.distinct()` after filtering the games to match the query. Additionally, the search results are now displayed as a grid, reusing the `games/game_grid.html` template.

### CODE REVIEW

**Review by frowenz — APPROVED** [review]
I now see a grid view when I search. I also am now longer able to get duplicates results.

Approved!

**Review by majorsylvie — APPROVED** [review]
Thank you for adding the requested changes! Happy to see you adding code comments to the `.distinct()` method, helpful for readability.

**Comment by ptlin25** [comment]
This pull request involved two relatively minor changes to the code. First, the `distinct()` method was added to filter the search results in order to remove duplicate results. Second, the search results view now uses the grid view template, so that it is consistent with the regular game viewing/browsing page.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Minor since this only involved changing one template. 
Thank you for the added code comment!

**Pull request merged**
