### PR TITLE
Add games nav item to the nav bar (minor)

### PR DESCRIPTION
**Pull request by frowenz**
In this PR, I added a `Games` item to the navbar, a small but essential change. See below:

Screenshot 2023-11-27 at 5 16 29 PM

### CODE REVIEW

**Review by willcravitz — APPROVED** [review]
A quick check confirmed that this works as expected. Thanks for making this update!

**Review by majorsylvie — APPROVED** [review]
Happy to have this added! Looks good to me.

**Comment by frowenz** [comment]
Closing comment:

Added a `Games` item to the navbar so navigating to the browse game page is quick.

**Comment by majorsylvie** [comment]
Issue Score: Excellent

Comments:
Great and overdue addition!
Thank you both for going through the PR process!

**Pull request merged**
