### PR TITLE
Redirecting from friend requests in inbox to profile page with the option to read, unread and delete notifications

### LINKED ISSUE #125: Adding directing from friend requests in inbox to profile page and add option to read and delete notifications
Clicking on a Friend Invitation in the inbox should direct to the sender profile page and that page should display options to accept or reject friendship. This builds on the implementing an inbox in #124. There should be buttons to read, unread and delete notifications and that should make them look different in the inbox.

### PR DESCRIPTION
**Pull request by omarelkashef**
This PR handles redirection from Notifications of FriendInvitation to profile pages of the sender. It also adds buttons to read, unread and delete notifications and uses bootstrap to display notifications in the inbox. Also, we added default message for friend request notifications.

### CODE REVIEW

**Review by henrietta-k — APPROVED** [review]
I tested it, and everything works great! Good job!

**Review by elizabethli31 — APPROVED** [review]
Love the bootstrap icons, and functionality works exactly as intended! This PR looks good to me for now, but I'd like for you guys make note of the default messages. The attribute is fine as a dict, but the code to get the message itself will probably change a decent amount to handle other messages. Also, a CSS page would make the style for user_inbox much easier to read and change later on. Good work!

**Comment by omarelkashef** [comment]
Closing Statement: We handled clicks on Notification of type FriendInvitation where they redirect to the sender's profile page. We also added buttons to read, unread and delete notifications in the inbox page as well as default message for friend request notifications.
@omarelkashef  worked on the backend logic and view functions
@24raniwalar  worked on the front end html, bootstrap and JS

**Comment by elizabethli31** [comment]
Issue Score: Excellent

Comments:
Large improvement to inbox frontend and functionalities - great job!

**Pull request merged**
